package com.company;

import java.util.HashMap;

public class Main {

    public static void main(String[] args) {
        HashMap<String, Patient> patients = new HashMap<>();
        patients.put("Ali", new Patient("Ali", "Atopiska vinterfötter"));
        patients.put("Betty", new Patient("Betty", "Blodförgiftning"));
        patients.put("Cecilia", new Patient("Cecilia", null));
        patients.put("Dennis", new Patient("Dennis", "Diskbråck"));
        patients.put("Eschwar", new Patient("Eschwar", "Epikondylit"));
        patients.put("Fadel", new Patient("Fadel", "Förkylning"));
        patients.put("Gunnar", new Patient("Gunnar", "Gallsten"));
        patients.put("Helena", new Patient("Helena", null));
        patients.put("Isabel", new Patient("Isabel", "Insomni"));
        patients.put("Jinghua", new Patient("Jinghua", "Järnbrist"));
        patients.put("Anna", new Patient("Anna"));
        patients.put("Bertil", new Patient("Bertil"));
        Patient p0 = patients.get("Ali");
        Patient p1 = patients.get("Betty");
        Patient p2 = patients.get("Cecilia");
        Patient p3 = patients.get("Dennis");
        Patient p4 = patients.get("Eschwar");
        Patient p5 = patients.get("Fadel");
        Patient p6 = patients.get("Gunnar");
        Patient p7 = patients.get("Helena");
        Patient p8 = patients.get("Isabel");
        Patient p9 = patients.get("Jinghua");
        Patient d0 = patients.get("Anna");
        Patient d1 = patients.get("Bertil");
        Patient.CheckPatient(d0, p0);
        Patient.CheckPatient(d0, p1);
        Patient.CheckPatient(d0, p2);
        Patient.CheckPatient(d0, p3);
        Patient.CheckPatient(d0, p4);
        Patient.CheckPatient(d0, p5);
        Patient.CheckPatient(d0, p6);
        Patient.CheckPatient(d0, p7);
        Patient.CheckPatient(d0, p8);
        Patient.CheckPatient(d0, p9);
        Patient.GetMedicine(d0, "Atopiska vinterfötter");
        Patient.TreatPatient(d1, p0, "Atopiska vinterfötter");
        Patient.CurePatient(p0);
        Patient.GetMedicine(d1, "Atopiska vinterfötter");
        Patient.TreatPatient(d0, p1, "Atopiska vinterfötter");
        Patient.CurePatient(p1);
        Patient.GetMedicine(d0, "Epikondylit");
        Patient.TreatPatient(d1, p4, "Epikondylit");
        Patient.CurePatient(p4);
        Patient.GetMedicine(d1, "Förkylning");
        Patient.TreatPatient(d0, p5, "Förkylning");
        Patient.CurePatient(p5);
        Patient.GetMedicine(d0, "Gallsten");
        p7.sDisease = "Gallsten";
        Patient.TreatPatient(d1, p7, "Gallsten");
        Patient.CurePatient(p7);
        Patient.GetMedicine(d1, "Halsfluss");
        p7.sDisease = "Halsfluss";
        Patient.TreatPatient(d0, p7, "Halsfluss");
        Patient.CurePatient(p7);
        Patient.GetMedicine(d0, "Järnbrist");
        Patient.TreatPatient(d1, p9, "Järnbrist");
        Patient.CurePatient(p9);
        Patient.CheckPatient(d1, p0);
        Patient.CheckPatient(d1, p1);
        Patient.CheckPatient(d1, p2);
        Patient.CheckPatient(d1, p3);
        Patient.CheckPatient(d1, p4);
        Patient.CheckPatient(d1, p5);
        Patient.CheckPatient(d1, p6);
        Patient.CheckPatient(d1, p7);
        Patient.CheckPatient(d1, p8);
        Patient.CheckPatient(d1, p9);
        Patient.GetMedicine(d0, "Blodförgiftning");
        Patient.TreatPatient(d1, p1, "Blodförgiftning");
        Patient.CurePatient(p1);
        Patient.GetMedicine(d1, "Diskbråck");
        Patient.TreatPatient(d0, p3, "Diskbråck");
        Patient.CurePatient(p3);
        Patient.GetMedicine(d0, "Gallsten");
        Patient.TreatPatient(d1, p6, "Gallsten");
        Patient.CurePatient(p6);
        Patient.GetMedicine(d1, "Insomni");
        Patient.TreatPatient(d0, p8, "Insomni");
        Patient.CurePatient(p8);
        Patient.CheckPatient(d1, p0);
        Patient.CheckPatient(d1, p1);
        Patient.CheckPatient(d1, p2);
        Patient.CheckPatient(d1, p3);
        Patient.CheckPatient(d1, p4);
        Patient.CheckPatient(d1, p5);
        Patient.CheckPatient(d1, p6);
        Patient.CheckPatient(d1, p7);
        Patient.CheckPatient(d1, p8);
        Patient.CheckPatient(d1, p9);
    }
}

